### ISSUE TITLE
Which login is using for this? 

### ISSUE THREAD

**Issue by arunreghu** [tensult/ngx-s3-upload#10]
After ngserve app open with a signup window. Which login is using for this or how to signup?

**Comment by anupsarkar177** [comment]
We don't have signup option for this, you need create an UserPool in the AWS Cognito service and  update your UserPool details manually in ngx-s3-upload app. You need create a user in the  Cognito UserPool, after that you will received an email with the password. Then sign-in with email and password and follow the rest instructions.
