### ISSUE TITLE
npm build failed

### ISSUE THREAD

**Issue by yaskshelat** [tensult/ngx-s3-upload#12]
Hi
I am to run npm install
This command creates a folder called "nodes_modules"

However the build is failed

i have attached the log file. 

[could](url
[2020-03-03T18_57_24_081Z-debug.log](https://github.com/tensult/ngx-s3-upload/files/4283068/2020-03-03T18_57_24_081Z-debug.log)
) you please help me out?

**Comment by yaskshelat** [comment]
Hi
I created a new VM and re-installed Node Js and tried to re-run the npm install. However it still fails.
I have attached updated logging report.

[2020-03-03T20_47_29_747Z-debug.log](https://github.com/tensult/ngx-s3-upload/files/4283569/2020-03-03T20_47_29_747Z-debug.log)

Could you please help ?
thanks

**Comment by koladilip** [comment]
@paragpoddar Please look into this.

**Comment by yaskshelat** [comment]
Thank you Dilip.
FYI
I followed instructions given here for setting up NPM on windows 10
[https://gist.github.com/jtrefry/fd0ea70a89e2c3b7779c](url)

I still have same issue

I also noticed one more thing, please see snapshot below
![image](https://user-images.githubusercontent.com/36253068/75889828-7cc9dd00-5dfb-11ea-88a4-8e42310a72ea.png)


It is trying to access one git repo and unable to access this. I am not sure if this error is due to that. How can we avoid this error?

regards
Yask

**Comment by yaskshelat** [comment]
Hi Dilip did you get a chance to review the error? do you need to change some configuration file related to angular in the git repo?
regards
Yask

**Comment by koladilip** [comment]
Sorry. We didn’t get time yesterday.

Thanks,
Dilip
Tensult
________________________________

**Comment by yaskshelat** [comment]
Hi Dilip sorry to bother again, did you get a time to look into this?

**Comment by paragpoddar** [comment]
Try these (worked for me):

Delete package-lock.json
Delete existing node_modules if downloaded before

install node-sass globally, 
`npm install -g node-sass`

`npm i`

**Comment by paragpoddar** [comment]
If you get rxjs error then try these:

convert `"rxjs": "^6.1.0"` to `"rxjs": "6.1.0"`

`npm i`

**Comment by yaskshelat** [comment]
Hi 
Thank you for your reply.
I tried sass install (your first reply), it worked ok for npm i (please see following snapshot) However when I tried to do npm start, it gives me webpack error as showed in a snapshot below

![image](https://user-images.githubusercontent.com/36253068/76168399-d278ef00-6145-11ea-97d0-29067252d01b.png)

I tried following solution given here https://github.com/webpack/webpack/issues/2131, and did following steps
npm remove webpack -g
npm i webpack --save-dev
npm run webpack

it doesnt work as well, any clues?
Thanks for your help

**Comment by yaskshelat** [comment]
> If you get rxjs error then try these:
> 
> convert `"rxjs": "^6.1.0"` to `"rxjs": "6.1.0"`
> 
> `npm i`

where do I put this? in some file or just in cmd ?

**Comment by yaskshelat** [comment]
Hi I tried to run 
npm audit fix --force

It fixed some of the errors, however i am still getting errors when I do npm start

i have attached log file
[2020-03-08T18_30_16_112Z-debug.log](https://github.com/tensult/ngx-s3-upload/files/4303680/2020-03-08T18_30_16_112Z-debug.log)

**Comment by paragpoddar** [comment]
> > If you get rxjs error then try these:
> > convert `"rxjs": "^6.1.0"` to `"rxjs": "6.1.0"`
> > `npm i`
> 
> where do I put this? in some file or just in cmd ?

**Comment by paragpoddar** [comment]
> > If you get rxjs error then try these:
> > convert `"rxjs": "^6.1.0"` to `"rxjs": "6.1.0"`
> > `npm i`
> 
> where do I put this? in some file or just in cmd ?

This is in package.json dependencies. But this one if you get rxjs error.

**Comment by yaskshelat** [comment]
Hi parag, hope things are great. I am still not able to resolve this, if you have any additional feedback based on the log I put, please let me know.
regards,
Yask

**Comment by yaskshelat** [comment]
Here is my most recent error. After doing npm i when I do npm start i get this error 
![image](https://user-images.githubusercontent.com/36253068/76917849-06b58380-689b-11ea-9527-1596b9d7bea0.png)

**Comment by yaskshelat** [comment]
> > If you get rxjs error then try these:
> > convert `"rxjs": "^6.1.0"` to `"rxjs": "6.1.0"`
> > `npm i`
> 
> where do I put this? in some file or just in cmd ?

Hi I chnaged rxjs in the package.json file and build was successful thank you so much

regard
Yask
