### ISSUE TITLE
first time sign in password change

### ISSUE THREAD

**Issue by yaskshelat** [tensult/ngx-s3-upload#13]
Hi
I created a new user in the cognito user pool, and signed in with temporary password. After this, it prompts me to change the password. When I change the password it repeatedly gives me following message

![image](https://user-images.githubusercontent.com/36253068/76919634-d8867280-689f-11ea-93a6-fd17486cab53.png)

why is that? Am I missing something?

**Comment by koladilip** [comment]
Looks like you have selected name as mandatory attribute while creating the user pool. We have set the only email to be compulsory. You can create a new pool as you can't modify the user pool attributes after creation or you need to modify the code to add name during the user confirmation.

<img width="1279" alt="UserPoolAttributesOfTensult" src="https://user-images.githubusercontent.com/33080863/76921988-66407d00-68f5-11ea-8688-3fa4544aaa58.png">
