### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by darichailu** [tensult/ngx-s3-upload#14]
Hi there,
Great work. This is exactly what I was looking for. I've a questions regarding user auth and access level. Is there a way to group your users based on permissions? I've a use-cases in which multiple users being able to see uploads/downloads. For instance, if user-1 uploads a file, user-2 can see the file uploaded and download it from a browser. Can this be handled from Congito or I've to make changes in the code for that functionality?

**Comment by koladilip** [comment]
This requires, new components to be introduced Lambda function and generate preSignedUrl on Lambda function.

**Comment by darichailu** [comment]
how about using cognito user pool grouping?

**Comment by koladilip** [comment]
Cognito user pool grouping, itself won't solve this but we can leverage it to build the solution.

**Comment by darichailu** [comment]
Okay thanks. I appreciate the help.

**Comment by darichailu** [comment]
Is there a way to open up security without breaking the app so that one login user able to access files of others? We only want to use this as depot/file share internally.

**Comment by koladilip** [comment]
Yes, need to modify the IAM role policy added to authenticated entity and bucket listing api prefix path. If you want we can do this as paid engagement as our company does projects for many other clients.

Thanks,
Dilip
Tensult
________________________________
