### ISSUE TITLE
Unable to find src/app/upload/config.ts

### ISSUE THREAD

**Issue by mavrick202** [tensult/ngx-s3-upload#4]
Hi,

The solutions looks very good and I am testing it. But when I have tested it, the HTML is standing at "Loading... Please wait" doing nothing. When I checked the steps again, I am unable to find "src/app/upload/config.ts" in the repo. Could you please help me what I am missing?

Rgds,
Sree.

**Comment by cornickj** [comment]
The file is src/app/auth/config.ts

**Comment by koladilip** [comment]
@mavrick202, I am sorry, we have updated the code but forgot to update the README.
You need to update [src/config/s3.ts](https://github.com/tensult/ngx-s3-upload/blob/master/src/config/s3.ts).
