### ISSUE TITLE
POST https://cognito-idp.us-east-1.amazonaws.com/ 400

### ISSUE THREAD

**Issue by edxxgardo** [tensult/ngx-s3-upload#6]
Hello,
I installed the app on my OSX and saw no errors during the start up. After configuring Cognito, I tried to authenticate a user without success because of a POST 400 error. Please check the screenshot.
It looks like the request is somehow wrong. Hope you can help. Thanks
<img width="1195" alt="screen shot 2018-10-02 at 10 55 54" src="https://user-images.githubusercontent.com/8612773/46342458-14d9fa80-c63b-11e8-943b-594be4d0abab.png">

**Comment by koladilip** [comment]
Have you created the user using Cognito user pool in AWS console?

**Comment by edxxgardo** [comment]
Yes, and I did it in different ways not knowing what the problem is. Check the screenshots attached. There you see the selections I made during the User Pool creation.

<img width="1241" alt="admin_or_not" src="https://user-images.githubusercontent.com/8612773/46355237-b7f13b00-c660-11e8-99b0-b810748a9f5d.png">
<img width="1250" alt="username_or_email" src="https://user-images.githubusercontent.com/8612773/46355238-b7f13b00-c660-11e8-9b24-7ba1a22f2217.png">
<img width="1248" alt="weird_username_when_using_email_for_login" src="https://user-images.githubusercontent.com/8612773/46355239-b889d180-c660-11e8-8724-ddd517764ed6.png">

**Comment by edxxgardo** [comment]
from my understanding, in the Angular app there is only the sign in (no signup) option implemented, that means I have to choose "Only allow administrators to create users" as seen in the first screenshot. Then, I have to choose i.e. "Email address or phone number" in the second screenshot and then create the user in "User and groups" as seen in the last screenshot. Is that all correct?

**Comment by edxxgardo** [comment]
ok. now it works
<img width="1246" alt="screen shot 2018-10-02 at 16 55 14" src="https://user-images.githubusercontent.com/8612773/46356966-1cfa6000-c664-11e8-8293-f7daa8cdfcaf.png">
 if I change from Chrome to Firefox (could it be the cache)? Nevertheless, there is another issue once logged in.

**Comment by koladilip** [comment]
> <img alt="screen shot 2018-10-02 at 16 55 14" width="1246" src="https://user-images.githubusercontent.com/8612773/46356966-1cfa6000-c664-11e8-8293-f7daa8cdfcaf.png">
> 
> ok. now it works if I change from Chrome to Firefox (could it be the cache)? Nevertheless, there is another issue once logged in and try to upload a file.

Make sure you have configured s3 config: https://github.com/tensult/ngx-s3-upload/blob/master/src/config/s3.ts
Please put your region and bucket name accordingly.
Also please change the default region to your s3 region: https://github.com/tensult/ngx-s3-upload/blob/master/src/app/upload/service.ts#L25

**Comment by edxxgardo** [comment]
The problem was with the default region in:  
https://github.com/tensult/ngx-s3-upload/blob/master/src/app/upload/service.ts#L25 

I uploaded a file and it worked fine. The only weird thing is the name of the folder created inside the folder stated in:
https://github.com/tensult/ngx-s3-upload/blob/master/src/config/s3.ts

Its the same weird number given by S3 to the user name created by me in the User Pool (838cafbf-63f9-4b8b-9582-1d3dc88eccca).

**Comment by koladilip** [comment]
> The problem was with the default region in:
> https://github.com/tensult/ngx-s3-upload/blob/master/src/app/upload/service.ts#L25
> 
> I uploaded a file and it worked fine. The only weird thing is the name of the folder created inside the folder stated in:
> https://github.com/tensult/ngx-s3-upload/blob/master/src/config/s3.ts
> 
> Its the same weird number given by S3 to the user name created by me in the User Pool (838cafbf-63f9-4b8b-9582-1d3dc88eccca).

You can change S3 folder structure logic in preparePutObjectRequest function:
https://github.com/tensult/ngx-s3-upload/blob/master/src/app/upload/service.ts#L45
You will also need to change the logic of listFiles:
https://github.com/tensult/ngx-s3-upload/blob/master/src/app/download/service.ts#L28

For security reasons, this.signedInUser.userId must be included in the path as this is used to define S3 bucket access in Cognito authenticated user role. And without this, one login user will be able to access files of others.

**Comment by koladilip** [comment]
@edxxgardo is this resolved?

**Comment by koladilip** [comment]
Resolving as no update for more than one month.

**Comment by kaayaltek** [comment]
hi I am getting the error "POST https://cognito-idp.us-east-1.amazonaws.com/ 400" when I am trying to add new password for the first time (but user name and temp pw are working I think that is why it is redirecting to the new pw page) and your screencast links are not working now bcs of the flash player issue
